In [1]:
# Q1 Create a data file by using Python random module with different random generator parameters. The data file must have 20000 X 10000 (rows X columns) in the data file. This data file to be used as database for realization of math and matrix operations in cloud computing lab assignments.

import numpy as np

#Generating 20000 x 10000 random data
data = np.random.randint(1, 100, size=(20000, 10000))

#Save to file
np.save('data_file.npy', data)

print("Data file created")
print("Shape:", data.shape)

Data file created
Shape: (20000, 10000)


In [2]:
# Q2. Write a program in Python to assign subsequent rows to matrix first row elements.

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = {}

for i, key in enumerate(matrix[0]):
    result[key] = matrix[1:, i]

result

{1: array([4, 7]), 2: array([5, 8]), 3: array([6, 9])}

In [3]:
# Q3 Write a program in Python to group similar elements into matrix.

data = [2,3,1,4,2,5,2,1,3,6,5,2,7,4,5]

#To store unique values in order
unique_values = []

#To store grouped rows
matrix = []

# Loop through each number in the list
for num in data:
    #If number already exists, add it to that group
    if num in unique_values:
        index = unique_values.index(num)
        matrix[index].append(num)
    #If number is new, create a new group
    else:
        unique_values.append(num)
        matrix.append([num])

#Displaying result
print("Grouped Matrix:")
for row in matrix:
    print(row)

Grouped Matrix:
[2, 2, 2, 2]
[3, 3]
[1, 1]
[4, 4]
[5, 5, 5]
[6]
[7]


In [5]:
# Q4 Matrix Addition and Subtraction

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
add = A + B

# Subtraction
sub = A - B

print("Addition:\n", add)
print("Subtraction:\n", sub)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [6]:
# Q5 Write a program in Python to create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.

import numpy as np

n = 4
matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        matrix[i][j] = 2 * (i + j)

matrix

array([[ 0,  2,  4,  6],
       [ 2,  4,  6,  8],
       [ 4,  6,  8, 10],
       [ 6,  8, 10, 12]])

In [7]:
# Q6 Row-wise Addition in Tuple Matrix

tuple_matrix = ((1, 2, 3),
                (4, 5, 6),
                (7, 8, 9))

row_sums = []

for row in tuple_matrix:
    row_sums.append(sum(row))

row_sums

[6, 15, 24]